# Generated by Django 4.0.4 on 2022-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField(max_length=64)),
                ("content", models.TextField(max_length=256)),
                ("priority", models.IntegerField(null=True)),
                ("reminder", models.DateTimeField(null=True)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("creation_time", models.TimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
