# Generated by Django 4.0.4 on 2022-05-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
