# Generated by Django 4.0.4 on 2022-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_priority_alter_note_reminder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
